### ISSUE TITLE
Logo is low resolution

### ISSUE THREAD

**Issue by appsforartists** [material-foundation/material-remixer-ios#61]
It looks like GitHub supports SVGs:

![](https://storage.googleapis.com/icons.google.com.a.appspot.com/google-assets/branding/product_logos/_quantum/res-export/logo_remixer_48px_clr.svg)

Can you update the logo in the README to use one?  The current one looks awful on high-res screens.

**Comment by chuga** [comment]
Fixed in https://github.com/material-foundation/material-remixer-ios/commit/954e289f51e4b3846926b2f98a96055fd995e6a1

**Comment by appsforartists** [comment]
👏
