### ISSUE TITLE
RMXColorVariable initializer is unused warning in Swift code

### ISSUE THREAD

**Issue by jverkoey** [material-foundation/material-remixer-ios#67]
```
RMXColorVariable(key: "squareColor", defaultValue: .red) {
  square.backgroundColor = $1
}
```

Gives the following warning:

![screen shot 2016-11-16 at 1 42 11 pm](https://cloud.githubusercontent.com/assets/45670/20360678/a4804c52-ac02-11e6-87af-8ee6115a07f3.png)

Unfortunately because this is an Objective-C API I'm not sure that we can annotate with `@discardableResult`. There might be an equivalent Objective-C API, but for now the best short-term fix is to use the following:

```
let _ = RMXColorVariable(key: "squareColor", defaultValue: .red) {
  square.backgroundColor = $1
}
```

**Comment by chuga** [comment]
This is now obsolete as Remixer now requires you to hold on to the variables you're using. The main goal of that change was to allow variables that are not in use to be dealloc'ed. I'll be updating the README soon.
